### ISSUE TITLE
Cannot build Debian installation disc

### ISSUE THREAD

**Issue by sorcer1122** [progmaticltd/homebox#131]
Hi,

I am having problems with building Debian ISO using the system.yml from here - https://homebox.readthedocs.io/en/latest/preseed/

Here is what I get:

Building cdbuild
Step 1/21 : FROM debian:stable
 ---> 882fa751e902
Step 2/21 : RUN echo 'deb http://deb.debian.org/debian/ stretch-backports main contrib non-free' >>/etc/apt/sources.list
 ---> Using cache
 ---> be836e20247b
Step 3/21 : RUN apt -qq update
 ---> Using cache
 ---> fbd0b46aedfb
Step 4/21 : RUN useradd -ms /bin/dash cdbuild
 ---> Using cache
 ---> 8f198caf60f0
Step 5/21 : RUN mkdir -p /home/cdbuild/misc/root/.ssh
 ---> Using cache
 ---> fb0b34a946e0
Step 6/21 : COPY --chown=cdbuild:cdbuild ./config/authorized_keys /home/cdbuild/misc/root/.ssh/authorized_keys
 ---> Using cache
 ---> b6546622f2eb
Step 7/21 : RUN apt -qq install -t stretch-backports -y simple-cdd
 ---> Using cache
 ---> ec3eea7eb7b8
Step 8/21 : RUN apt -qq install -t stretch-backports -y ansible
 ---> Using cache
 ---> 7db06386dfe2
Step 9/21 : COPY --chown=cdbuild:cdbuild ./misc /home/cdbuild/misc/
 ---> Using cache
 ---> 3f2158f7fc17
Step 10/21 : RUN rm -f /home/cdbuild/misc/readme.md
 ---> Using cache
 ---> e75876119edd
Step 11/21 : COPY --chown=cdbuild:cdbuild ./playbooks /home/cdbuild/playbooks/
 ---> Using cache
 ---> e43e0f02d502
Step 12/21 : COPY --chown=cdbuild:cdbuild ./config /home/cdbuild/config/
 ---> 394eae5a3a34
Step 13/21 : USER cdbuild
 ---> Running in 7ab7d7a6a400
Removing intermediate container 7ab7d7a6a400
 ---> 8ed8879a9d49
Step 14/21 : WORKDIR /home/cdbuild
 ---> Running in 976ff45a1bb7
Removing intermediate container 976ff45a1bb7
 ---> b9d0b0ae208a
Step 15/21 : COPY --chown=cdbuild:cdbuild ansible/ansible.cfg /home/cdbuild
 ---> 163509ba6c38
Step 16/21 : COPY --chown=cdbuild:cdbuild ansible/hosts.yml /home/cdbuild
 ---> 448278cdb8a3
Step 17/21 : RUN ansible-playbook -vv -i hosts.yml -l localhost playbooks/docker.yml
 ---> Running in 19e3c7de1c85
ansible-playbook 2.7.5
  config file = /home/cdbuild/ansible.cfg
  configured module search path = [u'/home/cdbuild/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
Using /home/cdbuild/ansible.cfg as config file
/home/cdbuild/hosts.yml did not meet host_list requirements, check plugin documentation if this is unexpected
/home/cdbuild/hosts.yml did not meet script requirements, check plugin documentation if this is unexpected

PLAYBOOK: docker.yml ***********************************************************
1 plays in playbooks/docker.yml

PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
task path: /home/cdbuild/playbooks/docker.yml:4
ok: [localhost]
META: ran handlers

TASK [build-iso : Create the working directory in /tmp/build-mydomain.com] ******
task path: /home/cdbuild/playbooks/roles/build-iso/tasks/main.yml:3
changed: [localhost] => changed=true 
  gid: 1000
  group: cdbuild
  mode: '0755'
  owner: cdbuild
  path: /tmp/build-mydomain.com
  size: 4096
  state: directory
  uid: 1000

TASK [build-iso : Copy the configuration file for mydomain.com] *****************
task path: /home/cdbuild/playbooks/roles/build-iso/tasks/main.yml:9
changed: [localhost] => changed=true 
  checksum: 2865bf6b05b3b7a513d8bb26c29984b442d18d76
  dest: /tmp/build-mydomain.com/common.conf
  gid: 1000
  group: cdbuild
  md5sum: 424503128a4211d18154c6558d15a08b
  mode: '0644'
  owner: cdbuild
  size: 6099
  src: /home/cdbuild/.ansible/tmp/ansible-tmp-1557782818.43-27653293662334/source
  state: file
  uid: 1000

TASK [build-iso : Copy the build script] ***************************************
task path: /home/cdbuild/playbooks/roles/build-iso/tasks/main.yml:15
changed: [localhost] => (item=build-mirror.sh) => changed=true 
  checksum: f84263890d653e632f0d20ddd37303a450a75a19
  dest: /tmp/build-mydomain.com/build-mirror.sh
  file: build-mirror.sh
  gid: 1000
  group: cdbuild
  md5sum: 5f1b98b47ab7ee8c78768a758af99d57
  mode: '0744'
  owner: cdbuild
  size: 514
  src: /home/cdbuild/.ansible/tmp/ansible-tmp-1557782819.49-18835295126653/source
  state: file
  uid: 1000
failed: [localhost] (item=build-cd.sh) => changed=false 
  file: build-cd.sh
  msg: 'AnsibleUndefinedVariable: ''dict object'' has no attribute ''version'''

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=1   

ERROR: Service 'cdbuild' failed to build: The command '/bin/sh -c ansible-playbook -vv -i hosts.yml -l localhost playbooks/docker.yml' returned a non-zero code: 2
Unable to find image 'cdbuild:latest' locally
docker: Error response from daemon: pull access denied for cdbuild, repository does not exist or may require 'docker login'.
See 'docker run --help'.

Looks like the problem is with main.yml, with 'copy the build script'
I would appreciate if anybody can help me with this. Thanks!

**Comment by arodier** [comment]
Hello Sorcer, I am going to have a look to this.
It has been long since I used this function.

**Comment by arodier** [comment]
Hello,
You seem to have an issue with your system.yml file.
Maybe the documentation is not clear, I will check this.
As an example, here the one I use for development:

```yaml
# System configuration sample 1: Encrypted hard drive
system:
  hostname: mail
  passphrase: A long passphrase to boot the system
  preseed: luks
  version: 9.6
  arch: amd64
  boot_timeout: 5   # In seconds

# Clock parameters
clock:
  utc: true
  ntp: true

# The proxy is optional. When specified, it is used to configure apt
network:
  domain: homebox.space
  proxy: false
  iface: auto

# Country and locales definition
country:
  code: uk
  timezone: Europe/London

locale:
  id: en_GB
  language: en
  country: UK
  charset: UTF-8
  keymap: gb

# Repository specific values
repo:
  release: stretch
  main: ftp.uk.debian.org
  security: security.debian.org
  sections: main contrib non-free

# Accounts information
# You can choose a strong password here,
# The public key will be copied on the CD image so you can logon directly onto the system
root:
  password: u2H4j4PK5rXKdB
  pubkey: /home/andre/.ssh/arodier.rsa.pub

# Where to place the ISO image once it is built.
# Here an example with libvirt. or can be /tmp as well...
cdimage:
  destination: '/var/lib/libvirt/iso'

# Debug: as it states
debug: true


```
