### ISSUE TITLE
Dovecot conf.d files error

### ISSUE THREAD

**Issue by sorcer1122** [progmaticltd/homebox#148]
OK got to the first error while running mail.yml playbook, which I cannot fix:

TASK [dovecot : Create dovecot conf.d configuration files] *********************************************************************************************************************************
failed: [homebox] (item=10-auth.conf) => changed=false
file: 10-auth.conf
msg: 'AnsibleUndefinedVariable: ''dict object'' has no attribute ''username_chars'''
failed: [homebox] (item=10-master.conf) => changed=false
file: 10-master.conf
msg: 'AnsibleUndefinedVariable: ''dict object'' has no attribute ''log_access'''
changed: [homebox] => (item=10-mail.conf)
changed: [homebox] => (item=10-logging.conf)
changed: [homebox] => (item=15-lda.conf)
changed: [homebox] => (item=15-mailboxes.conf)
changed: [homebox] => (item=20-managesieve.conf)
changed: [homebox] => (item=20-imap.conf)
changed: [homebox] => (item=20-lmtp.conf)
changed: [homebox] => (item=90-sieve.conf)
changed: [homebox] => (item=90-plugin.conf)
changed: [homebox] => (item=90-quota.conf)

RUNNING HANDLER [dovecot : Restart dovecot] ************************************************************************************************************************************************

PLAY RECAP *********************************************************************************************************************************************************************************
homebox : ok=339 changed=84 unreachable=0 failed=1
localhost : ok=0 changed=0 unreachable=0 failed=0

Where can I find this dict object?

**Comment by arodier** [comment]
The variable username_chars is defined in the file dovecot/defaults/main.yml

```yaml
# Default dovecot packages to install
dovecot:
  ...
  # Authorized characters for the username
  username_chars: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ01234567890.-_@
```

Have you redefined the dovecot variable somewhere? What is your version of Ansible ?

**Comment by sorcer1122** [comment]
Found it! Mine is exactly the same as yours, I have not changed it and did not define it elsewhere.

My ansible is 2.7.7

**Comment by arodier** [comment]
Maybe try to run Ansible with -vv flag, and see the output?

**Comment by krimaeus** [comment]
I remember it failing on the `msg: 'AnsibleUndefinedVariable: ''dict object'' has no attribute ''log_access'''` part so I used ripgrep to recursively check the homebox directory. The result was that - as the error says - there was no `log_access` attribute.

As it isn't referenced anywhere (some kind of leftover?) I figured I could just remove the `or mail.log_access` from this line.
https://github.com/progmaticltd/homebox/blob/036c899c90beab6e17d8a0e4d6b9b9fa7089e8ee/install/playbooks/roles/dovecot/templates/conf.d/10-master.conf#L75

As for the first error, I don't remember getting that one so I'll try to rerun the playbook to see what I get.

**Comment by arodier** [comment]
Yes, you are right. I understand this is now a bug. You can remove the 
condition. I renamed a variable, and did not check this one.

I will commit a fix today soon, it is minor.

Kind regards,
André

**Comment by arodier** [comment]
If you do not want to wait for the fix, perhaps you can try this:
```
{% if mail.import.active or access_check.active %}
```

**Comment by arodier** [comment]
The access_check bug has been fixed in the commit #149. For the one related to dovecot, I cannot confirm it. I have replayed the whole installation playbook from scratch.

Here the mail parameters I am using:

```yaml
###############################################################################
# Email related options
mail:
  max_attachment_size: 25   # In megabytes
  autoconfig: true          # Support Thunderbird automatic configuration
  autodiscover: false       # Support MS Outlook automatic configuration (uses https)
  quota:
    default: 1G             # Maximum allowed mailbox size for your users.
                            # The safe maximum value will be automatically computed in a next version.
  #############################################################################
  # Postfix options
  postfix:
    mynetworks: ~
  #############################################################################
  antispam:                 # Check inbound and outbound emails for viruses
    webui:                  # rspamd web interface
      active: false         # Activate or not
      allow:                # a list of IP address that can access the web interface
        - 92.19.253.41
        - 2002:5c13:fd29:0:2158:b6b0:1c6f:6c59
  antivirus:                # Check inbound and outbound emails for viruses
    active: true            # or false
    action: drop            # Action to do when a virus is found in an email: bounce or drop
                            # be careful, bouncing external emails is a way to expose clamav usage
    quarantine: yes         # Place emails with a virus in quarantine, for further analysis
  impersonate:              # Activate dovecot "master" user feature, ideal for families and communities
    active: false           # https://wiki2.dovecot.org/Authentication/MasterUsers
  #############################################################################
  # Virtual folders
  virtual_folders:          # Create virtual IMAP folders, like flagged,
    active: false           # deleted, unread, conversations, etc.
                            # It is useful to put a limit here if you have a lot of messages
                            # and limited hardware resources. It is set to 10 years by default
  #############################################################################
  import:                   # If you have users with "import" email active scripts, set this flag to true
    active: true            # A master user, with reduced rights will be created, to append imported emails
                            # in user's mailboxes.
  #############################################################################
  # Dovecot / solr FTS (Full Text search)
  fts:
    active: false
 #############################################################################
  # Fail2ban parameters
  fail2ban:
    time: 14400
```
