### ISSUE TITLE
VPS DNS Managed Subdomain

### ISSUE THREAD

**Issue by gdbaldw** [progmaticltd/homebox#362]
Please, walk through the DNS records for a DigitalOcean project. HomeBox should manage its subdomain DNS, but DigitalOcean DNS manages the domain example.com, with...

site1.example.com A-record to "Old Droplet1"
site2.example.com A-record to "Old Droplet2"
mail.example.com  A-record to "New Droplet for HomeBox, Debian 10"

**So, do I also add A and NS records?** I tried several ways, and now it set at:

main.mail.example.com A-record to "New Droplet for HomeBox, Debian 10"
mail.mytradingpartner.com NS-record to main.mail.mytradingpartner.com

Config files and console out are below:

```
<hosts.yml>
all:
  hosts:
    homebox:
      ansible_host: mail.example.com
      ansible_user: root
      ansible_port: 22

<system.yml>
network:
  domain: example.com
  hostname: mail.example.com
```
Install fails at:
```
TASK [dns-server-bind : Ensure the main record resolves to me] ***************************************************************************************
changed: [homebox]
...
FAILED - RETRYING: Check DNS propagation (10 retries left).
...
```
